export enum USER_ROLE {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    MEMBER = 'MEMBER',
}

export enum TASK_STATUS {
    TODO = 'TODO',
    IN_PROGRESS = 'IN_PROGRESS',
    DONE = 'DONE',
}

export enum ACTIVITY_LOG_TYPES {
    USER = 'USER',
    TEAM = 'TEAM',
    PROJECT = 'PROJECT',
    TASK = 'TASK',
    MESSAGE = 'MESSAGE',
}

export enum ACTIVITY_LOG_SUB_TYPES { 
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',

    TEAM_CREATED = 'TEAM_CREATED',
    TEAM_UPDATED = 'TEAM_UPDATED',
    TEAM_DELETED = 'TEAM_DELETED',

    PROJECT_CREATED = 'PROJECT_CREATED',
    PROJECT_UPDATED = 'PROJECT_UPDATED',    
    PROJECT_DELETED = 'PROJECT_DELETED',

    TASK_CREATED = 'TASK_CREATED',    
    TASK_UPDATED = 'TASK_UPDATED',    
    TASK_DELETED = 'TASK_DELETED',

    MESSAGE_SENT = 'MESSAGE_SENT',
}